import java.util.*;
class Example{
	public static void main(String []args){
		Scanner input=new Scanner(System.in);
		System.out.println();
		System.out.println();
		System.out.println("                       _____                      _     ______        _     _              ");
		System.out.println("                      / ____|                    | |   |  ____|      | |   (_)             ");
		System.out.println("                     | (___  _ __ ___   __ _ _ __| |_  | |__ __ _ ___| |__  _  ___  _ __   ");
		System.out.println("                      \\___ \\| '_ ` _ \\ / _` | '__| __| |  __/ _` / __| '_ \\| |/ _ \\| '_ \\  ");
		System.out.println("                      ____) | | | | | | (_| | |  | |_  | | | (_| \\__ \\ | | | | (_) | | | | ");
		System.out.println("                     |_____/|_| |_| |_|\\__,_|_|   \\__| |_|  \\__,_|___/_| |_|_|\\___/|_| |_| ");
		System.out.println();
		System.out.println();
		System.out.print("                     Date : ");
		String date=input.next();
		System.out.println();
		System.out.print("                     Customer Name : ");
		String name=input.next();
		System.out.println();
		System.out.println("                    -----------------------------------------------------------------------");
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("                                      _____    ___ _    _     _       ");
		System.out.println("                                     |_   _|__/ __| |_ (_)_ _| |_ ___ ");
		System.out.println("                                       | ||___\\__ \\ ' \\| | '_|  _(_-< ");
		System.out.println("                                       |_|    |___/_||_|_|_|  \\__/__/ ");
		System.out.println();
		System.out.println();
		System.out.print("                     Number of T-Shirts : ");
		int qty1=input.nextInt();
		System.out.println();
		System.out.print("                     Unit Price of T-Shirt : ");
		float price1=input.nextFloat();
		System.out.println();
		float amount1=((price1)*(qty1)*95)/100f;
		System.out.print("                     Discount Rate (%) : 5");
		System.out.println();
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Description         |     QTY     |    Unit Price   |    Amount   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | T-Shirt             |      "+qty1+"      |      "+price1+"      |    "+amount1+"   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println();
		System.out.println();
		System.out.println("                    -----------------------------------------------------------------------");
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("                                       _____                               ");
		System.out.println("                                      |_   _| _ _____ __ _____ ___ _ _ ___ ");
		System.out.println("                                        | || '_/ _ \\ V  V (_-</ -_) '_(_-< ");
		System.out.println("                                        |_||_| \\___/\\_/\\_//__/\\___|_| /__/ ");
		System.out.println();
		System.out.println();
		System.out.print("                     Number of Trousers : ");
		int qty2=input.nextInt();
		System.out.println();
		System.out.print("                     Unit Price of Trouser : ");
		float price2=input.nextFloat();
		System.out.println();
		float amount2=((price2)*(qty2)*100)/100f;
		System.out.print("                     Discount Rate (%) : 0");
		System.out.println();
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Description         |     QTY     |    Unit Price   |    Amount   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Trouser             |      "+qty2+"      |      "+price2+"     |    "+amount2+"   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println();
		System.out.println();
		System.out.println("                    -----------------------------------------------------------------------");
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("                                                ___ _    _     _       ");
		System.out.println("                                               / __| |_ (_)_ _| |_ ___ ");
		System.out.println("                                               \\__ \\ ' \\| | '_|  _(_-< ");
		System.out.println("                                               |___/_||_|_|_|  \\__/__/ ");
		System.out.println();
		System.out.println();
		System.out.print("                     Number of Shirts : ");
		int qty3=input.nextInt();
		System.out.println();
		System.out.print("                     Unit Price of Shirt : ");
		float price3=input.nextFloat();
		System.out.println();
		float amount3=((price3)*(qty3)*95)/100f;
		System.out.print("                     Discount Rate (%) : 5");
		System.out.println();
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Description         |     QTY     |    Unit Price   |    Amount   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Shirt               |      "+qty3+"      |      "+price3+"     |    "+amount3+"   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println();
		System.out.println();
		System.out.println("                    -----------------------------------------------------------------------");
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("                                                ___ _            _       ");
		System.out.println("                                               / __| |_  ___ _ _| |_ ___ ");
		System.out.println("                                               \\__ \\ ' \\/ _ \\ '_|  _(_-< ");
		System.out.println("                                               |___/_||_\\___/_|  \\__/__/ ");
		System.out.println();
		System.out.println();
		System.out.print("                     Number of Shorts : ");
		int qty4=input.nextInt();
		System.out.println();
		System.out.print("                     Unit Price of Short : ");
		float price4=input.nextFloat();
		System.out.println();
		float amount4=((price4)*(qty4)*97)/100f;
		System.out.print("                     Discount Rate (%) : 3");
		System.out.println();
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Description         |     QTY     |    Unit Price   |    Amount   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Short               |      "+qty4+"      |      "+price4+"      |    "+amount4+"   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println();
		System.out.println();
		System.out.println("                    -----------------------------------------------------------------------");
		System.out.println();
		System.out.println();
		System.out.println();
		float total=amount1+amount2+amount3+amount4;
		System.out.println("                     +-------------------------------------------------------------------+");
		System.out.println("                     |            ___ _ _ _   ___                                        |");
		System.out.println("                     |           | _ |_) | | / __|_  _ _ __  _ __  __ _ _ _ _  _         |");
		System.out.println("                     |           | _ \\ | | | \\__ \\ || | '  \\| '  \\/ _` | '_| || |        |");
		System.out.println("                     |           |___/_|_|_| |___/\\_,_|_|_|_|_|_|_\\__,_|_|  \\_, |        |");
		System.out.println("                     |                                                      |__/         |");
		System.out.println("                     |                                                                   |");
		System.out.println("                     | Customer : "+name+"                              Date : "+date+" |");
		System.out.println("                     |                                                                   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Description         |     QTY     |    Unit Price   |    Amount   |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     |                     |             |                 |             |");
		System.out.println("                     | T-Shirt             |      "+qty1+"      |      "+price1+"      |    "+amount1+"   |");
		System.out.println("                     |                     |             |                 |             |");
		System.out.println("                     | Trouser             |      "+qty2+"      |      "+price2+"     |    "+amount2+"   |");
		System.out.println("                     |                     |             |                 |             |");
		System.out.println("                     | Shirt               |      "+qty3+"      |      "+price3+"     |    "+amount3+"   |");
		System.out.println("                     |                     |             |                 |             |");
		System.out.println("                     | Short               |      "+qty4+"      |      "+price4+"      |    "+amount4+"   |");
		System.out.println("                     |                     |             |                 |             |");
		System.out.println("                     +---------------------+-------------+-----------------+-------------+");
		System.out.println("                     | Total                                               |    "+total+"   |");
		System.out.println("                     +-----------------------------------------------------+-------------+");	
	}
}
